// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cluster/proto/cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskLeaderRequest) Reset() {
	*x = AskLeaderRequest{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskLeaderRequest) ProtoMessage() {}

func (x *AskLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskLeaderRequest.ProtoReflect.Descriptor instead.
func (*AskLeaderRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *AskLeaderRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AskLeaderRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type AskLeaderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term           int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderNodeName string                 `protobuf:"bytes,3,opt,name=leader_node_name,json=leaderNodeName,proto3" json:"leader_node_name,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AskLeaderResponse) Reset() {
	*x = AskLeaderResponse{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskLeaderResponse) ProtoMessage() {}

func (x *AskLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskLeaderResponse.ProtoReflect.Descriptor instead.
func (*AskLeaderResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *AskLeaderResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AskLeaderResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AskLeaderResponse) GetLeaderNodeName() string {
	if x != nil {
		return x.LeaderNodeName
	}
	return ""
}

func (x *AskLeaderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AskVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskVoteRequest) Reset() {
	*x = AskVoteRequest{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskVoteRequest) ProtoMessage() {}

func (x *AskVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskVoteRequest.ProtoReflect.Descriptor instead.
func (*AskVoteRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *AskVoteRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AskVoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type AskVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteNodeName  string                 `protobuf:"bytes,3,opt,name=vote_node_name,json=voteNodeName,proto3" json:"vote_node_name,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskVoteResponse) Reset() {
	*x = AskVoteResponse{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskVoteResponse) ProtoMessage() {}

func (x *AskVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskVoteResponse.ProtoReflect.Descriptor instead.
func (*AskVoteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *AskVoteResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AskVoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AskVoteResponse) GetVoteNodeName() string {
	if x != nil {
		return x.VoteNodeName
	}
	return ""
}

func (x *AskVoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BroadcastLeaderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term           int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderNodeName string                 `protobuf:"bytes,3,opt,name=leader_node_name,json=leaderNodeName,proto3" json:"leader_node_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastLeaderRequest) Reset() {
	*x = BroadcastLeaderRequest{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastLeaderRequest) ProtoMessage() {}

func (x *BroadcastLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastLeaderRequest.ProtoReflect.Descriptor instead.
func (*BroadcastLeaderRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastLeaderRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *BroadcastLeaderRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *BroadcastLeaderRequest) GetLeaderNodeName() string {
	if x != nil {
		return x.LeaderNodeName
	}
	return ""
}

type BroadcastLeaderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term           int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderNodeName string                 `protobuf:"bytes,3,opt,name=leader_node_name,json=leaderNodeName,proto3" json:"leader_node_name,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastLeaderResponse) Reset() {
	*x = BroadcastLeaderResponse{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastLeaderResponse) ProtoMessage() {}

func (x *BroadcastLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastLeaderResponse.ProtoReflect.Descriptor instead.
func (*BroadcastLeaderResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastLeaderResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *BroadcastLeaderResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *BroadcastLeaderResponse) GetLeaderNodeName() string {
	if x != nil {
		return x.LeaderNodeName
	}
	return ""
}

func (x *BroadcastLeaderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HeartbeatRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Term           int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderNodeName string                 `protobuf:"bytes,3,opt,name=leader_node_name,json=leaderNodeName,proto3" json:"leader_node_name,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HeartbeatResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartbeatResponse) GetLeaderNodeName() string {
	if x != nil {
		return x.LeaderNodeName
	}
	return ""
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoteCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FuncName      string                 `protobuf:"bytes,3,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Param         *anypb.Any             `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	Sync          bool                   `protobuf:"varint,5,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteCallRequest) Reset() {
	*x = RemoteCallRequest{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCallRequest) ProtoMessage() {}

func (x *RemoteCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCallRequest.ProtoReflect.Descriptor instead.
func (*RemoteCallRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *RemoteCallRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RemoteCallRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RemoteCallRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *RemoteCallRequest) GetParam() *anypb.Any {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *RemoteCallRequest) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type RemoteCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FuncName      string                 `protobuf:"bytes,3,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Err           string                 `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteCallResponse) Reset() {
	*x = RemoteCallResponse{}
	mi := &file_cluster_proto_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCallResponse) ProtoMessage() {}

func (x *RemoteCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCallResponse.ProtoReflect.Descriptor instead.
func (*RemoteCallResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *RemoteCallResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RemoteCallResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RemoteCallResponse) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *RemoteCallResponse) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RemoteCallResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_cluster_proto_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1bcluster/proto/cluster.proto\x12\acluster\x1a\x19google/protobuf/any.proto\"C\n" +
	"\x10AskLeaderRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\"\x88\x01\n" +
	"\x11AskLeaderResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12(\n" +
	"\x10leader_node_name\x18\x03 \x01(\tR\x0eleaderNodeName\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"A\n" +
	"\x0eAskVoteRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\"\x82\x01\n" +
	"\x0fAskVoteResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12$\n" +
	"\x0evote_node_name\x18\x03 \x01(\tR\fvoteNodeName\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"s\n" +
	"\x16BroadcastLeaderRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12(\n" +
	"\x10leader_node_name\x18\x03 \x01(\tR\x0eleaderNodeName\"\x8e\x01\n" +
	"\x17BroadcastLeaderResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12(\n" +
	"\x10leader_node_name\x18\x03 \x01(\tR\x0eleaderNodeName\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"C\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\"\x88\x01\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12(\n" +
	"\x10leader_node_name\x18\x03 \x01(\tR\x0eleaderNodeName\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x9f\x01\n" +
	"\x11RemoteCallRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tfunc_name\x18\x03 \x01(\tR\bfuncName\x12*\n" +
	"\x05param\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05param\x12\x12\n" +
	"\x04sync\x18\x05 \x01(\bR\x04sync\"\xa0\x01\n" +
	"\x12RemoteCallResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tfunc_name\x18\x03 \x01(\tR\bfuncName\x12,\n" +
	"\x06result\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x06result\x12\x10\n" +
	"\x03err\x18\x05 \x01(\tR\x03err2\xf7\x02\n" +
	"\x0eClusterService\x12B\n" +
	"\tAskLeader\x12\x19.cluster.AskLeaderRequest\x1a\x1a.cluster.AskLeaderResponse\x12<\n" +
	"\aAskVote\x12\x17.cluster.AskVoteRequest\x1a\x18.cluster.AskVoteResponse\x12T\n" +
	"\x0fBroadcastLeader\x12\x1f.cluster.BroadcastLeaderRequest\x1a .cluster.BroadcastLeaderResponse\x12F\n" +
	"\tHeartbeat\x12\x19.cluster.HeartbeatRequest\x1a\x1a.cluster.HeartbeatResponse(\x010\x01\x12E\n" +
	"\n" +
	"RemoteCall\x12\x1a.cluster.RemoteCallRequest\x1a\x1b.cluster.RemoteCallResponseB1Z/github.com/caiflower/common-tools/cluster/protob\x06proto3"

var (
	file_cluster_proto_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_cluster_proto_rawDescData []byte
)

func file_cluster_proto_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_cluster_proto_rawDesc), len(file_cluster_proto_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_cluster_proto_rawDescData
}

var file_cluster_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cluster_proto_cluster_proto_goTypes = []any{
	(*AskLeaderRequest)(nil),        // 0: cluster.AskLeaderRequest
	(*AskLeaderResponse)(nil),       // 1: cluster.AskLeaderResponse
	(*AskVoteRequest)(nil),          // 2: cluster.AskVoteRequest
	(*AskVoteResponse)(nil),         // 3: cluster.AskVoteResponse
	(*BroadcastLeaderRequest)(nil),  // 4: cluster.BroadcastLeaderRequest
	(*BroadcastLeaderResponse)(nil), // 5: cluster.BroadcastLeaderResponse
	(*HeartbeatRequest)(nil),        // 6: cluster.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 7: cluster.HeartbeatResponse
	(*RemoteCallRequest)(nil),       // 8: cluster.RemoteCallRequest
	(*RemoteCallResponse)(nil),      // 9: cluster.RemoteCallResponse
	(*anypb.Any)(nil),               // 10: google.protobuf.Any
}
var file_cluster_proto_cluster_proto_depIdxs = []int32{
	10, // 0: cluster.RemoteCallRequest.param:type_name -> google.protobuf.Any
	10, // 1: cluster.RemoteCallResponse.result:type_name -> google.protobuf.Any
	0,  // 2: cluster.ClusterService.AskLeader:input_type -> cluster.AskLeaderRequest
	2,  // 3: cluster.ClusterService.AskVote:input_type -> cluster.AskVoteRequest
	4,  // 4: cluster.ClusterService.BroadcastLeader:input_type -> cluster.BroadcastLeaderRequest
	6,  // 5: cluster.ClusterService.Heartbeat:input_type -> cluster.HeartbeatRequest
	8,  // 6: cluster.ClusterService.RemoteCall:input_type -> cluster.RemoteCallRequest
	1,  // 7: cluster.ClusterService.AskLeader:output_type -> cluster.AskLeaderResponse
	3,  // 8: cluster.ClusterService.AskVote:output_type -> cluster.AskVoteResponse
	5,  // 9: cluster.ClusterService.BroadcastLeader:output_type -> cluster.BroadcastLeaderResponse
	7,  // 10: cluster.ClusterService.Heartbeat:output_type -> cluster.HeartbeatResponse
	9,  // 11: cluster.ClusterService.RemoteCall:output_type -> cluster.RemoteCallResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cluster_proto_cluster_proto_init() }
func file_cluster_proto_cluster_proto_init() {
	if File_cluster_proto_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_cluster_proto_rawDesc), len(file_cluster_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_proto_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto_cluster_proto = out.File
	file_cluster_proto_cluster_proto_goTypes = nil
	file_cluster_proto_cluster_proto_depIdxs = nil
}
