// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: test_greeter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TestGreeter_SayHello_FullMethodName = "/cluster.TestGreeter/SayHello"
)

// TestGreeterClient is the client API for TestGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestGreeterClient interface {
	SayHello(ctx context.Context, in *TestHelloRequest, opts ...grpc.CallOption) (*TestHelloResponse, error)
}

type testGreeterClient struct {
	cc grpc.ClientConnInterface
}

func NewTestGreeterClient(cc grpc.ClientConnInterface) TestGreeterClient {
	return &testGreeterClient{cc}
}

func (c *testGreeterClient) SayHello(ctx context.Context, in *TestHelloRequest, opts ...grpc.CallOption) (*TestHelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestHelloResponse)
	err := c.cc.Invoke(ctx, TestGreeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestGreeterServer is the server API for TestGreeter service.
// All implementations must embed UnimplementedTestGreeterServer
// for forward compatibility
type TestGreeterServer interface {
	SayHello(context.Context, *TestHelloRequest) (*TestHelloResponse, error)
	mustEmbedUnimplementedTestGreeterServer()
}

// UnimplementedTestGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedTestGreeterServer struct {
}

func (UnimplementedTestGreeterServer) SayHello(context.Context, *TestHelloRequest) (*TestHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTestGreeterServer) mustEmbedUnimplementedTestGreeterServer() {}

// UnsafeTestGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestGreeterServer will
// result in compilation errors.
type UnsafeTestGreeterServer interface {
	mustEmbedUnimplementedTestGreeterServer()
}

func RegisterTestGreeterServer(s grpc.ServiceRegistrar, srv TestGreeterServer) {
	s.RegisterService(&TestGreeter_ServiceDesc, srv)
}

func _TestGreeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestGreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestGreeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestGreeterServer).SayHello(ctx, req.(*TestHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestGreeter_ServiceDesc is the grpc.ServiceDesc for TestGreeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestGreeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.TestGreeter",
	HandlerType: (*TestGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _TestGreeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_greeter.proto",
}
