// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: test_greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestHelloRequest) Reset() {
	*x = TestHelloRequest{}
	mi := &file_test_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHelloRequest) ProtoMessage() {}

func (x *TestHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHelloRequest.ProtoReflect.Descriptor instead.
func (*TestHelloRequest) Descriptor() ([]byte, []int) {
	return file_test_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *TestHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TestHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestHelloResponse) Reset() {
	*x = TestHelloResponse{}
	mi := &file_test_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHelloResponse) ProtoMessage() {}

func (x *TestHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHelloResponse.ProtoReflect.Descriptor instead.
func (*TestHelloResponse) Descriptor() ([]byte, []int) {
	return file_test_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *TestHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestHelloResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_test_greeter_proto protoreflect.FileDescriptor

const file_test_greeter_proto_rawDesc = "" +
	"\n" +
	"\x12test_greeter.proto\x12\acluster\"&\n" +
	"\x10TestHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x11TestHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId2P\n" +
	"\vTestGreeter\x12A\n" +
	"\bSayHello\x12\x19.cluster.TestHelloRequest\x1a\x1a.cluster.TestHelloResponseB1Z/github.com/caiflower/common-tools/cluster/protob\x06proto3"

var (
	file_test_greeter_proto_rawDescOnce sync.Once
	file_test_greeter_proto_rawDescData []byte
)

func file_test_greeter_proto_rawDescGZIP() []byte {
	file_test_greeter_proto_rawDescOnce.Do(func() {
		file_test_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_greeter_proto_rawDesc), len(file_test_greeter_proto_rawDesc)))
	})
	return file_test_greeter_proto_rawDescData
}

var file_test_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_greeter_proto_goTypes = []any{
	(*TestHelloRequest)(nil),  // 0: cluster.TestHelloRequest
	(*TestHelloResponse)(nil), // 1: cluster.TestHelloResponse
}
var file_test_greeter_proto_depIdxs = []int32{
	0, // 0: cluster.TestGreeter.SayHello:input_type -> cluster.TestHelloRequest
	1, // 1: cluster.TestGreeter.SayHello:output_type -> cluster.TestHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_greeter_proto_init() }
func file_test_greeter_proto_init() {
	if File_test_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_greeter_proto_rawDesc), len(file_test_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_greeter_proto_goTypes,
		DependencyIndexes: file_test_greeter_proto_depIdxs,
		MessageInfos:      file_test_greeter_proto_msgTypes,
	}.Build()
	File_test_greeter_proto = out.File
	file_test_greeter_proto_goTypes = nil
	file_test_greeter_proto_depIdxs = nil
}
