// Code generated by caiflower generator; DO NOT EDIT.
package model

import (
	"github.com/caiflower/common-tools/pkg/basic"
	"github.com/uptrace/bun"
)

// TaskBak generate from table task_bak
type TaskBak struct {
	bun.BaseModel `bun:"table:task_bak"`
	ID            string     `bun:"id,pk,notnull" json:"id"`             // 任务ID
	RequestID     string     `bun:"request_id" json:"requestID"`         // 请求ID
	TaskName      string     `bun:"task_name" json:"taskName"`           // 任务名称
	Input         string     `bun:"input" json:"input"`                  // 任务输入参数
	Output        string     `bun:"output" json:"output"`                // 任务输出结果
	Worker        string     `bun:"worker" json:"worker"`                // 执行任务的工作节点
	Retry         int8       `bun:"retry" json:"retry"`                  // 剩余重试次数
	RetryInterval int32      `bun:"retry_interval" json:"retryInterval"` // 重试间隔(秒)
	Urgent        bool       `bun:"urgent" json:"urgent"`                // 是否紧急任务(0:否, 1:是)
	State         string     `bun:"state" json:"state"`                  // 任务状态
	Description   string     `bun:"description" json:"description"`      // 任务描述
	CreateTime    basic.Time `bun:"create_time" json:"createTime"`       // 创建时间
	UpdateTime    basic.Time `bun:"update_time" json:"updateTime"`       // 更新时间
	Status        int8       `bun:"status" json:"status"`                // 任务状态(0:禁用, 1:启用)
}

type TaskBakFilter struct {
	Page        int      `json:"page"`
	PageSize    int      `json:"pageSize"`
	DisablePage bool     `json:"disablePage"`
	Orders      []string `json:"orders,omitempty"`

	ID            []string     `json:"id,omitempty"`
	RequestID     []string     `json:"requestID,omitempty"`
	TaskName      []string     `json:"taskName,omitempty"`
	Input         []string     `json:"input,omitempty"`
	Output        []string     `json:"output,omitempty"`
	Worker        []string     `json:"worker,omitempty"`
	Retry         []int8       `json:"retry,omitempty"`
	RetryInterval []int32      `json:"retryInterval,omitempty"`
	Urgent        []bool       `json:"urgent,omitempty"`
	State         []string     `json:"state,omitempty"`
	Description   []string     `json:"description,omitempty"`
	CreateTime    []basic.Time `json:"createTime,omitempty"`
	UpdateTime    []basic.Time `json:"updateTime,omitempty"`
	Status        []int8       `json:"status,omitempty"`
}

func (f *TaskBakFilter) GetPage() (offset int, limit int, disable bool) {
	if f.DisablePage {
		return 0, 0, true
	}
	page := f.Page
	if page <= 0 {
		page = 1
	}
	size := f.PageSize
	if size <= 0 {
		size = 10
	}
	return (page - 1) * size, size, false
}

func (f *TaskBakFilter) WithID(v ...string) *TaskBakFilter {
	f.ID = v
	return f
}

func (f *TaskBakFilter) WithRequestID(v ...string) *TaskBakFilter {
	f.RequestID = v
	return f
}

func (f *TaskBakFilter) WithTaskName(v ...string) *TaskBakFilter {
	f.TaskName = v
	return f
}

func (f *TaskBakFilter) WithInput(v ...string) *TaskBakFilter {
	f.Input = v
	return f
}

func (f *TaskBakFilter) WithOutput(v ...string) *TaskBakFilter {
	f.Output = v
	return f
}

func (f *TaskBakFilter) WithWorker(v ...string) *TaskBakFilter {
	f.Worker = v
	return f
}

func (f *TaskBakFilter) WithRetry(v ...int8) *TaskBakFilter {
	f.Retry = v
	return f
}

func (f *TaskBakFilter) WithRetryInterval(v ...int32) *TaskBakFilter {
	f.RetryInterval = v
	return f
}

func (f *TaskBakFilter) WithUrgent(v ...bool) *TaskBakFilter {
	f.Urgent = v
	return f
}

func (f *TaskBakFilter) WithState(v ...string) *TaskBakFilter {
	f.State = v
	return f
}

func (f *TaskBakFilter) WithDescription(v ...string) *TaskBakFilter {
	f.Description = v
	return f
}

func (f *TaskBakFilter) WithCreateTime(v ...basic.Time) *TaskBakFilter {
	f.CreateTime = v
	return f
}

func (f *TaskBakFilter) WithUpdateTime(v ...basic.Time) *TaskBakFilter {
	f.UpdateTime = v
	return f
}

func (f *TaskBakFilter) WithStatus(v ...int8) *TaskBakFilter {
	f.Status = v
	return f
}

func (f *TaskBakFilter) WithPage(page int) *TaskBakFilter {
	f.Page = page
	return f
}

func (f *TaskBakFilter) WithPageSize(pageSize int) *TaskBakFilter {
	f.PageSize = pageSize
	return f
}

func (f *TaskBakFilter) WithDisablePage(disable bool) *TaskBakFilter {
	f.DisablePage = disable
	return f
}

func (f *TaskBakFilter) WithOrders(orders ...string) *TaskBakFilter {
	f.Orders = orders
	return f
}

func (f *TaskBakFilter) Filter(db bun.IDB) *bun.SelectQuery {
	q := db.NewSelect()
	if len(f.Status) == 0 {
		q.Where("status>0")
	}
	if len(f.ID) > 0 {
		if len(f.ID) == 1 {
			q.Where("id = ?", f.ID[0])
		} else {
			q.Where("id IN (?)", bun.In(f.ID))
		}
	}
	if len(f.RequestID) > 0 {
		if len(f.RequestID) == 1 {
			q.Where("request_id = ?", f.RequestID[0])
		} else {
			q.Where("request_id IN (?)", bun.In(f.RequestID))
		}
	}
	if len(f.TaskName) > 0 {
		if len(f.TaskName) == 1 {
			q.Where("task_name = ?", f.TaskName[0])
		} else {
			q.Where("task_name IN (?)", bun.In(f.TaskName))
		}
	}
	if len(f.Input) > 0 {
		if len(f.Input) == 1 {
			q.Where("input = ?", f.Input[0])
		} else {
			q.Where("input IN (?)", bun.In(f.Input))
		}
	}
	if len(f.Output) > 0 {
		if len(f.Output) == 1 {
			q.Where("output = ?", f.Output[0])
		} else {
			q.Where("output IN (?)", bun.In(f.Output))
		}
	}
	if len(f.Worker) > 0 {
		if len(f.Worker) == 1 {
			q.Where("worker = ?", f.Worker[0])
		} else {
			q.Where("worker IN (?)", bun.In(f.Worker))
		}
	}
	if len(f.Retry) > 0 {
		if len(f.Retry) == 1 {
			q.Where("retry = ?", f.Retry[0])
		} else {
			q.Where("retry IN (?)", bun.In(f.Retry))
		}
	}
	if len(f.RetryInterval) > 0 {
		if len(f.RetryInterval) == 1 {
			q.Where("retry_interval = ?", f.RetryInterval[0])
		} else {
			q.Where("retry_interval IN (?)", bun.In(f.RetryInterval))
		}
	}
	if len(f.Urgent) > 0 {
		if len(f.Urgent) == 1 {
			q.Where("urgent = ?", f.Urgent[0])
		} else {
			q.Where("urgent IN (?)", bun.In(f.Urgent))
		}
	}
	if len(f.State) > 0 {
		if len(f.State) == 1 {
			q.Where("state = ?", f.State[0])
		} else {
			q.Where("state IN (?)", bun.In(f.State))
		}
	}
	if len(f.Description) > 0 {
		if len(f.Description) == 1 {
			q.Where("description = ?", f.Description[0])
		} else {
			q.Where("description IN (?)", bun.In(f.Description))
		}
	}
	if len(f.CreateTime) > 0 {
		if len(f.CreateTime) == 1 {
			q.Where("create_time = ?", f.CreateTime[0].Time())
		} else if len(f.CreateTime) == 2 {
			q.Where("create_time BETWEEN ? AND ?", f.CreateTime[0].Time(), f.CreateTime[1].Time())
		}
	}
	if len(f.UpdateTime) > 0 {
		if len(f.UpdateTime) == 1 {
			q.Where("update_time = ?", f.UpdateTime[0].Time())
		} else if len(f.UpdateTime) == 2 {
			q.Where("update_time BETWEEN ? AND ?", f.UpdateTime[0].Time(), f.UpdateTime[1].Time())
		}
	}
	if len(f.Status) > 0 {
		if len(f.Status) == 1 {
			q.Where("status = ?", f.Status[0])
		} else {
			q.Where("status IN (?)", bun.In(f.Status))
		}
	}
	if len(f.Orders) > 0 {
		q.Order(f.Orders...)
	} else {
		q.Order("id desc")
	}
	return q
}
