// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: hello.proto

package webtest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IServiceClient is the client API for IService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Search2(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type iServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIServiceClient(cc grpc.ClientConnInterface) IServiceClient {
	return &iServiceClient{cc}
}

func (c *iServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.IService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) Search2(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.IService/Search2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IServiceServer is the server API for IService service.
// All implementations must embed UnimplementedIServiceServer
// for forward compatibility
type IServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Search2(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedIServiceServer()
}

// UnimplementedIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIServiceServer struct {
}

func (UnimplementedIServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedIServiceServer) Search2(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search2 not implemented")
}
func (UnimplementedIServiceServer) mustEmbedUnimplementedIServiceServer() {}

// UnsafeIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IServiceServer will
// result in compilation errors.
type UnsafeIServiceServer interface {
	mustEmbedUnimplementedIServiceServer()
}

func RegisterIServiceServer(s grpc.ServiceRegistrar, srv IServiceServer) {
	s.RegisterService(&IService_ServiceDesc, srv)
}

func _IService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_Search2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).Search2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IService/Search2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).Search2(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IService_ServiceDesc is the grpc.ServiceDesc for IService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IService",
	HandlerType: (*IServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _IService_Search_Handler,
		},
		{
			MethodName: "Search2",
			Handler:    _IService_Search2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
